version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    volumes:
      - ./migrations/0001_create_table_clients.sql:/docker-entrypoint-initdb.d/0001_create_table_clients.sql